[FIX] Remove ZSTD need for VKD3D
Heroic-Games-Launcher/HeroicGamesLauncher pull request #1514
Opened 2022-06-22 10:29 UTC by flavioislima

### Changed
- Use Bottles VKD3D instead of Valves since it uses tar.gz compression;
- Remove dependencies for Linux packages
- Fixed English translations for warnings.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2022-06-22 14:34 UTC, Nocccer approved these changes
LGTM

2022-06-22 14:58 UTC, imLinguin approved these changes

2022-07-04 21:58 UTC, CommandMC requested changes
Looks good, only missing a `yarn i18next`

2022-07-10 18:43 UTC, CommandMC approved these changes

2022-07-15 12:15 UTC, merged