Allow for EOS Overlay management directly in the launcher
Heroic-Games-Launcher/HeroicGamesLauncher pull request #1526
Opened 2022-06-26 13:57 UTC by CommandMC

Plans for this:
- [ ] Make it easy to manage EOS Overlay data (right now this is in the Advanced settings), e.g. checking for updates, removing the overlay
- [ ] Allow toggling the overlay on a prefix-by-prefix basis (or globally on Windows)

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2022-07-06 12:52 UTC, CommandMC commented on src/screens/Game/GameSubMenu/index.tsx
> +                      setEosOverlayInstalling(false)
Ideally this would be a helper function somewhere, I'm just not quite sure how to create those here

2022-07-07 13:17 UTC, flavioislima commented on src/screens/Game/GameSubMenu/index.tsx
> +                onClick={async () => {
This is definetelly doing a lot of stuff.
Move whats inside the onClick to a `useCallback` function like:
```
const handleEosOverlay = React.useCallback(async () => {
add rest of the function.

}, [add dependecies here])
```

then change the onclick to:
`onClick={handleEosOverlay}`

2022-07-07 13:19 UTC, flavioislima requested changes
Looks good just think that onClick should be put somewhere else.

2022-07-10 18:38 UTC, flavioislima approved these changes
Pretty good stuff 👍🏽

2022-07-10 18:56 UTC, merged