Improve README and developer experience
Heroic-Games-Launcher/HeroicGamesLauncher pull request #1807
Opened 2022-09-12 15:47 UTC by CommandMC

This PR makes changes to the README (see commit about it for details), brings VSCode's configuration up to speed again, and resolves a warning (which wasn't an issue in our use case, but it's still nice to not see that every time you run `yarn dev` IMO)

I've tested the Content Security Policy a bit (see notes on commit adding it) and it seems to not introduce any issues, but if you have some time, please verify this :^)

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [X] Tested the feature and it's working on a current and clean install.
- [X] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2022-09-12 19:01 UTC, Nocccer requested changes
Pretty good work. Somehow the Patreon picture is not loaded for me.

![image](https://user-images.githubusercontent.com/61798668/189734166-e3c1f9eb-e35c-40ed-879a-b30016ffdb42.png)

2022-09-12 19:01 UTC, Nocccer approved these changes
Ok second time it loaded...

2022-09-12 19:44 UTC, CommandMC commented
The badges very rarely fail to load, that's true. Sadly can't do anything about that in the README, the user will just have to reload

2022-09-14 06:59 UTC, flavioislima commented on README.md
> -You can add the [**Raul Dipeas**](https://rauldipeas.surge.sh) _personal_ [`apt` repository](https://github.com/rauldipeas/apt-repository):
I think some people use this repo, we should keep it.

2022-09-14 12:20 UTC, flavioislima approved these changes
Good stuff! :D

2022-09-14 12:22 UTC, merged