[Tech] Lint all TS/TSX files in the project
Heroic-Games-Launcher/HeroicGamesLauncher pull request #2512
Opened 2023-03-02 19:22 UTC by CommandMC

We weren't linting files outside of the "main" code (namely, tests). Now we do!

Note that I've disabled some rules for test files specifically that might be annoying there (you often "stub out" a function or use `any` in a mock, we don't want ESLint yelling at us there)

This has the nice benefit of our IDEs (at least Webstorm) no longer providing false errors on `backend/`, `common/` and `frontend/` imports, as those test files now actually belong to a project, as well as those weird errors around `.replaceAll` disappearing

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [X] Tested the feature and it's working on a current and clean install.
- [X] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [X] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2023-03-03 00:03 UTC, Nocccer requested changes
Left some question. Besides that lgtm.
It still does not solve the problem marking absolute paths as errors in vscode.

2023-03-04 20:07 UTC, CommandMC commented on .eslintignore
> -i18next-parser.config.js
As mentioned in the commit removing it, the file only contained (1) files that we now want to lint (tests, vite config) and (2) files that get ignored by ESLint anyways

2023-03-04 20:46 UTC, CommandMC commented
> It still does not solve the problem marking absolute paths as errors in vscode.

Yup, can confirm that now. Strange, it *should* know where those paths point to now

2023-03-05 00:01 UTC, Nocccer commented on .eslintignore
> -i18next-parser.config.js
OK makes sense. I know that there is a problem with prettier and flatpak folders...

2023-03-05 00:02 UTC, Nocccer commented
> > It still does not solve the problem marking absolute paths as errors in vscode.
> 
> Yup, can confirm that. Strange, it _should_ know where those paths point to now

The error comes from tsconfig. Somehow the typescript extensions can't solve this for `.test.ts` files.

2023-03-05 00:21 UTC, Nocccer approved these changes

2023-03-06 22:34 UTC, merged