[Shortcuts] Use icon from api for gog shortcuts
Heroic-Games-Launcher/HeroicGamesLauncher pull request #2528
Opened 2023-03-09 17:46 UTC by imLinguin

This is simple addition that will load icon from API instead of using squashed cover:

Before:  
![obraz](https://user-images.githubusercontent.com/62100117/224111278-156d9902-5250-4b5c-becf-92624dee49e9.png)

After:  
![obraz](https://user-images.githubusercontent.com/62100117/224111297-b2384acb-dd1c-4301-bcb3-957d6b9ce11f.png)

It may be necessary to manually delete icon from icons directory so new ones can be pulled.

**Note** squashed covers will still be used as fallback if for some reason API call fails

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2023-03-10 01:56 UTC, redromnon commented
The existing icons use jpg format. There might be a case where the user has forgotten they already have a shortcut and try to add it anyway from the game page' game actions menu.

This will result in the new/modified shortcut that uses the wrong image's path with a png extension since a jpg image exists and it fails to show the icon.

2023-03-10 02:01 UTC, redromnon commented
> It may be necessary to manually delete icon from icons directory so new ones can be pulled.
I think you're right.

2023-03-10 02:02 UTC, redromnon commented
> It may be necessary to manually delete icon from icons directory so new ones can be pulled.

I think you're right.

2023-03-10 20:12 UTC, Nocccer requested changes
I would find it better if the art_square holds the correct image. We check runners here again. We should avoid that as much as possible. The gameInfo should contain all correct informations no matter which runner.

2023-03-10 20:43 UTC, imLinguin commented
The issue with making it generic is that Epic doesn't provide such images. Also `art_square` is a left over name from Epic API, which is a vertical image as far as I know.

2023-03-11 13:37 UTC, Nocccer commented
> The issue with making it generic is that Epic doesn't provide such images. Also `art_square` is a left over name from Epic API, which is a vertical image as far as I know.

Epic provides everything like gog does. Else the add to steam feature had never worked for both. I would say we could refactor the gameinfo images and give them proper naming. Something like a new type:

```typescript
interface Images {
  banner?: string
  icon?: string
  portrait?: string
}

interface GameInfo {
  // ...
  images: Images
  // ...
}
```

2023-03-11 14:14 UTC, imLinguin commented
What I mean is epic doesn't have icons like GOG. 

we are limited to those fields in it's case

```json
"art_cover": "https://cdn1.epicgames.com/item/df2da503f2074f078f8090da3c27ec47/EGS_BioShockInfiniteCompleteEdition_MassMediaGames_S1_2560x1440-bf29199cfe7a76f62965f582571024f6_2560x1440-bf29199cfe7a76f62965f582571024f6",
"art_square": "https://cdn1.epicgames.com/item/df2da503f2074f078f8090da3c27ec47/EGS_BioShockInfiniteCompleteEdition_MassMediaGames_S2_1200x1600-bcf5e88c8afb572ec00d3ed231ec26e5",
```

2023-03-11 17:19 UTC, Nocccer commented
> ```json
> https://cdn1.epicgames.com/item/df2da503f2074f078f8090da3c27ec47/EGS_BioShockInfiniteCompleteEdition_MassMediaGames_S2_1200x1600-bcf5e88c8afb572ec00d3ed231ec26e5
> ```

I understand. It still does not make my idea impossible. For Epic icon and portrait is the same url for gog this differ. The good thing about is that we can use just this information without cehcking which runner we are pulling images. Gameinfo should be generic and the runner libs should care about correct image urls.

2023-03-12 14:24 UTC, Nocccer approved these changes
Ok lets approve for now and i will start the refactor of it today.

2023-03-12 14:32 UTC, CommandMC commented
I mean, nothing prevents you from pushing your changes onto this branch as well

2023-03-12 15:14 UTC, imLinguin commented
Exactly

2023-03-18 10:17 UTC, imLinguin commented
I'll try to add the structure like you suggested @Nocccer

2023-03-18 10:29 UTC, Nocccer commented
> I'll try to add the structure like you suggested @Nocccer 

Sure. Else i will do but didn't find time yet.

2023-03-24 03:42 UTC, arielj commented
@Nocccer should we merge this one and do the refactor later or do you think it's better to wait? I'm confused with the latest messages of the conversation

2023-03-24 04:20 UTC, Nocccer commented
Merge and refactor later

2023-03-24 12:14 UTC, merged