Add Italian translation
Heroic-Games-Launcher/HeroicGamesLauncher pull request #281
Opened 2021-03-29 00:54 UTC by Giovix92

If anyone spots something wrong in my translations, feel free to make edits! 😄

2021-04-07 18:53 UTC, LukeVader-IV requested changes
some changes, some are needed, most are just suggestions

2021-04-07 18:53 UTC, LukeVader-IV commented on public/locales/it/translation.json
> +  "nogames": "Nessun gioco provato",
```suggestion
  "nogames": "Nessun gioco trovato",
```

2021-04-07 18:56 UTC, Giovix92 commented on public/locales/it/gamepage.json
> +    "size": "Dimensione",
well another alternative could be "Peso", but I guess "Dimensione" is the right choice here, since it's referring to the package's size.

2021-04-07 18:57 UTC, Giovix92 commented on public/locales/it/gamepage.json
> +      "stop": "In esecuzione (Stop)"
I'd replace "Giocando" with "In esecuzione" though. I mean, "Giocando" doesn't have too much sense (i don't know if you're native italian or not), also EGS uses "In esecuzione".

2021-04-07 18:58 UTC, Giovix92 commented on public/locales/it/translation.json
> +  "nogames": "Nessun gioco provato",
My bad, misspelled here.

2021-04-07 18:58 UTC, Giovix92 commented on public/locales/it/login.json
> +    "placeholder": "Incolla qui il numero SID"
Yeah, both are correct imho.

2021-04-07 18:59 UTC, Giovix92 commented on public/locales/it/gamepage.json
> +  "enabled": "Abilitato",
Also true. Nice tip!

2021-04-07 19:48 UTC, LukeVader-IV commented on public/locales/it/gamepage.json
> +      "stop": "In esecuzione (Stop)"
In my opinion it should be this as it's a translation of "Play now" and "Playing", while I'm Italian i've only learned it as my language 3. could you maybe clarify how this wouldn't make much sense?

2021-04-07 19:56 UTC, LukeVader-IV commented on public/locales/it/gamepage.json
> +    "size": "Dimensione",
yeah i couldn't find an alternative word for it, now i'm wondering what they would say once i go study computer science in Milan

2021-04-07 19:57 UTC, LukeVader-IV commented on public/locales/it/gamepage.json
> +      "message": "Quest'operazione puo' richiedere molto tempo, sei sicuro?",
DW, me neither lol

2021-04-07 20:16 UTC, LukeVader-IV commented on public/locales/it/login.json
> +    "placeholder": "Incolla qui il numero SID"
up to you if you wanna accept the suggested change or not

2021-04-07 22:56 UTC, Giovix92 commented on public/locales/it/gamepage.json
> +      "stop": "In esecuzione (Stop)"
well the game is still an "application" that's actually running, so "In esecuzione" actually refers to the game itself. "Giocando" for me sounds a bit weird to put in. As a native speaker, I'd put "In esecuzione".

2021-04-09 10:59 UTC, adityaruplaha approved these changes
LGTM, merging.

2021-04-09 11:02 UTC, merged

2021-04-09 11:02 UTC, adityaruplaha commented
Congratulations on your first contribution! 🎉