Get steam deck comaptibility
Heroic-Games-Launcher/HeroicGamesLauncher pull request #2829
Opened 2023-06-30 15:18 UTC by kohend

Steam Deck compatibility from Steam's API

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [X] Tested the feature and it's working on a current and clean install.
- [X] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [X] Created / Updated Tests (If necessary)
- [X] Created / Updated documentation (If necessary)

2023-07-01 02:16 UTC, Nocccer approved these changes
Nice. Left some opinion but nothing that holds back this feature.

2023-07-01 02:16 UTC, Nocccer commented on src/common/types.ts
> +export interface SteamDeckComp {
I know my preference, but would love to combine protondb and this together.

2023-07-01 22:15 UTC, kohend commented
![image](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/309245/63cd6e0f-c353-49d9-8708-5725ca0dcca4)

2023-07-04 18:23 UTC, Nocccer requested changes
I don't like the frontend implementation. Something is wrong here.
Maybe not your fault but i would make a new component like HowLonToBeat and Gamescore.
The component combines apple crossover compatiblity and proton/steamdeck compatibility.
If you don't know how, i could do that.

2023-07-04 18:23 UTC, Nocccer commented on src/backend/wiki_game_info/wiki_game_info.ts
> +    const steamID = gamesdb?.steamID ? gamesdb.steamID : ''
```suggestion
    if (isLinux) {
      const steamID = pcgamingwiki?.steamID ?? gamesdb?.steamID
      const [protondb, steamdeck] = await Promise.all([     
        getInfoFromProtonDB(steamID),
        getSteamDeckComp(steamID)
    ])
    }
```

2023-07-04 19:35 UTC, Nocccer commented
@arielj @flavioislima Can you look over the frontend implementation? 
Code in the backend is already done and tested.

2023-07-05 10:39 UTC, kohend reviewed
Looks better than what I did, well, I'm not a UI person

2023-07-05 10:39 UTC, kohend commented on src/frontend/screens/Game/GamePage/index.tsx
> +  CheckCircleOutline,
Perhaps the check will be better if it's the full and not the outline version?

2023-07-05 10:39 UTC, kohend commented on src/frontend/screens/Game/GamePage/index.tsx
> +        style={{ marginLeft: '5px', cursor: 'not-allowed' }}
Perhaps color these to make them more differentiated?

2023-07-05 10:39 UTC, kohend commented on src/backend/wiki_game_info/wiki_game_info.ts
> +      const steamID = pcgamingwiki?.steamID ?? gamesdb?.steamID
If there's a new default and the gamesdb is a fallback, I think the fallback should be tested as well.

2023-07-14 12:18 UTC, flavioislima approved these changes
I think looks good using the icons on the UI 👍🏽

2023-07-14 12:18 UTC, merged