[Refactor] Move the library status/filters out of the GlobalContext into a LibraryContext
Heroic-Games-Launcher/HeroicGamesLauncher pull request #3151
Opened 2023-10-22 03:27 UTC by arielj

I started working on implementing some redesign for the library and noticed the current state management of the library is spread all over the place:
- most state is in GlobalState
- some state is in Library
- some state is in the children of the library

The state of the library doesn't need to be global, moving that out saves extra re-renderings, like re-rendering the sidebar when the search changes. Also, decoupling the different components will make it easier for me to implement some of the design changes for the filtering. It also makes the code more consistent, ActionIcons was updating the local storage of the browser to store the values of some filters but the other filters were updated by GlobalState.

Now all these:
- search text
- platform filter
- store filter
- sorting
- layout
- visibility filter

are handled by the Library component and shared with a context to also avoid prop drilling

One more thing I noticed and fixed: the platform filter and the toggle to show/hide non-available games were not getting stored

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2023-10-22 03:28 UTC, arielj commented on src/frontend/components/UI/ActionIcons/index.tsx
> +  } = useContext(LibraryContext)
some state came from the global context, some from props, now it's all from the library context

2023-10-22 03:47 UTC, arielj commented on src/frontend/state/GlobalState.tsx
> -    }
more than a year ago we migrated the `epic` filter to be called `legendary`, by now any user should already have the correct store filter saved in the local storage so we can remove this migration workaround

2023-10-23 13:30 UTC, flavioislima commented
Could not find any other issue.

2023-10-23 13:30 UTC, flavioislima requested changes
Only issue is with the favorites.

2023-10-24 03:56 UTC, arielj commented
> Testing this one here now. One issue I found is that the favorites are not being updated until you restart the app. First I added a few games to it and then clicking on the favorites button was showing nothing. Then After going to the General settings and changing the first lane to 'Favorites' made it work. But then after adding more favorites won't work until restart. ![image](https://user-images.githubusercontent.com/26871415/277349862-01df329f-ac0f-4bdf-8dc2-d85b4b6c42d4.png)

thanks for testing, just pushed a fix for that

2023-10-24 09:21 UTC, flavioislima approved these changes
Works perfectly now. I noticed a bit of performance improvement as well when changing filters, layout, etc.
Maybe we won't need mobx or recoil in the short term anymore? 👀 
something to think about.

2023-10-25 03:15 UTC, merged