Arch/Manjaro install
Heroic-Games-Launcher/HeroicGamesLauncher pull request #317
Opened 2021-04-19 05:50 UTC by CleoMenezes

New way to install via pacman file.

2021-04-20 04:56 UTC, paulohenriquesn reviewed
good

2021-04-20 04:57 UTC, paulohenriquesn approved these changes
I liked it

2021-04-22 17:30 UTC, adityaruplaha requested changes

2021-04-22 17:30 UTC, adityaruplaha commented on README.md
>  Otherwise you can install it via your prefered AUR helper, e.g. yay.
Please move this above the newly added section.

2021-05-09 00:11 UTC, CleoMenezes commented
> @CleoMenezes can you please address the comments so that we can merge this? Thanks.

How can I do it?

2021-05-09 03:26 UTC, adityaruplaha commented
> > @CleoMenezes can you please address the comments so that we can merge this? Thanks.
> 
> How can I do it?

Just make changes to the file based on my feedback?

2021-05-09 03:30 UTC, adityaruplaha requested changes

2021-05-09 03:30 UTC, adityaruplaha commented on README.md
> +Navigate to the file directory and run:
```suggestion
Navigate to the directory containing the downloaded file and run:
```
This would be more grammatically appropriate in my opinion.

2021-05-09 03:30 UTC, adityaruplaha commented on README.md
> +Installation via the pacman file:
Please move this part below below the AUR helper part.

2021-05-09 17:25 UTC, CleoMenezes reviewed
Done!

2021-06-01 03:50 UTC, adityaruplaha commented
Still not fixed though, please address review comments. @CleoMenezes

2021-06-07 10:28 UTC, adityaruplaha commented
Closing due to inactivity.

2021-06-07 10:28 UTC, closed without merging