[Tech] Deduplicate our Workflows
Heroic-Games-Launcher/HeroicGamesLauncher pull request #3198
Opened 2023-11-04 21:12 UTC by CommandMC

Definitely not betting on this working first-try, ignore this for now

- The "install-deps" action is used to have one place to declare (common) dependencies for building
- The build-base workflow is used for a generic "build Heroic for all platforms and upload the results" step (since we do that multiple times as well)
- Job strategies were used wherever possible to not repeat (nearly) the same steps for 3 OSs

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2023-11-05 11:59 UTC, flavioislima commented on .github/actions/install-deps/action.yml
I only vote for us to use NPM here instead of yarn since it gave me several issues during the latest release and did not work at all making me waste more than 2h debugging. While changing to npm make it work on first try.
Also, about the worrying of the lock file, the npm uses yarn.lock file if it is available since v7:
```This command installs a package and any packages that it depends on. If the package has a package-lock, or an npm shrinkwrap file, or a yarn lock file, the installation of dependencies will be driven by that```

2023-11-05 11:59 UTC, flavioislima requested changes
Just change the install deps to use npm and we are fine 👍🏽

2023-11-05 12:43 UTC, CommandMC commented on .github/actions/install-deps/action.yml
This PR's intent was *just* to deduplicate our files, not to change them in any way

Moving to npm (or any other package manager) requires changes not just in this files, and is best left to its own PR (#3192)

2023-11-06 00:18 UTC, CommandMC commented on .github/actions/install-deps/action.yml
Oh hang on, I see what you mean now, we were using npm for some of these files while using yarn for others (I had this patch laying around for a bit, so I didn't notice this change)

Should be fixed now

2023-11-08 10:37 UTC, flavioislima commented on .github/actions/install-deps/action.yml
perfect. Thanks!

2023-11-08 10:37 UTC, flavioislima approved these changes
Pretty good stuff!

2023-11-08 10:37 UTC, merged