[Fix] Print sideload game install dir in logs
Heroic-Games-Launcher/HeroicGamesLauncher pull request #3591
Opened 2024-02-24 03:01 UTC by arielj

This PR fixes an issue with sideloaded games printing `Installed in: undefined` instead of the real app folder.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2024-02-24 04:08 UTC, Etaash-mathamsetty approved these changes
lgtm

2024-03-03 14:59 UTC, CommandMC requested changes
I would be more in favor of making sideloaded games' GameInfo consistent with the others (reporting the install path in `install.install_path`, instead of having to look at a different property to get that info)

2024-03-09 20:45 UTC, flavioislima approved these changes
lgtm

2024-03-16 17:37 UTC, arielj commented
> I would be more in favor of making sideloaded games' GameInfo consistent with the others (reporting the install path in `install.install_path`, instead of having to look at a different property to get that info)

I agree with that, but I'd rather have that in another PR since it's a more complicated change (it requires fixing the game info for games that are already installed and updating other parts of the code to use `install_path` instead). This PR is just meant to fix the info in the logs, refactoring the sideload games sounds way more complicated just to get this thing working.

2024-03-16 18:42 UTC, CommandMC commented
It is definitely more work, and I get why you'd not want to do it (in this PR, and in general). I just worry that "patch-work" fixes like this will make the code harder to read & work with. I mean, the fact that this mistake was made in the first place already proves this.

I've said "Oh well, fine for now, we'll fix it up later" too many times, but I guess this'll be number <too many times + 1>

2024-03-16 19:58 UTC, merged