Add Wine Dependency information to Readme
Heroic-Games-Launcher/HeroicGamesLauncher pull request #3686
Opened 2024-04-08 17:13 UTC by termdisc

For non-flatpaks, refer to Wine dependencies.

<--- Put the description here --->

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2024-04-14 10:16 UTC, Gamertech commented
Think it's because of the extra brackets around the link. Compare to the link directly below your commit.

2024-04-19 08:51 UTC, CommandMC requested changes
I'm not sure how we want to proceed, with this & #3687 doing the same thing

2024-04-19 08:51 UTC, CommandMC commented on README.md
> +#### Non-Flatpak Installations
There's a trailing space here (that's why Prettier is not passing)
```suggestion
#### Non-Flatpak Installations
```

2024-04-26 19:54 UTC, flavioislima commented
This information was added on another PR.
thanks for the contribution.

2024-04-26 19:54 UTC, closed without merging