chore: improve whisky discoverability on mac
Heroic-Games-Launcher/HeroicGamesLauncher pull request #3747
Opened 2024-05-12 06:20 UTC by WangEdward

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3728#issuecomment-2105946706
Use the same version detection method as [Whisky](https://github.com/Whisky-App/Whisky/blob/57082e3187a4b4481f1c80c85506f939e41bbded/WhiskyKit/Sources/WhiskyKit/WhiskyWine/WhiskyWineInstaller.swift)

Ping @ahmed2m. I do not have Whisky installed. Please download the CI build to see if this works.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2024-05-12 17:15 UTC, ahmed2m commented
I can't seem to get the CI build working, it just says right after installing
`“Heroic” is damaged and can’t be opened. You should move it to the Trash.`

2024-05-14 09:42 UTC, flavioislima commented
> I can't seem to get the CI build working, it just says right after installing `“Heroic” is damaged and can’t be opened. You should move it to the Trash.`

that is because the build file is not signed, you need to run this command from the macOS terminal for it to work:
`xattr -d com.apple.quarantine path_to_Heroic.app`

2024-05-19 22:33 UTC, JoshuaBrest requested changes

2024-05-19 22:33 UTC, JoshuaBrest commented on src/backend/utils/compatibility_layers.ts
> +  const whiskyWinePath = `${userHome}/Library/Application Support/com.isaacmarovitz.Whisky/Libraries`
use `path.join`

2024-05-19 22:33 UTC, JoshuaBrest commented on src/backend/utils/compatibility_layers.ts
> +        lib: `${dirname(whiskyWineBin)}/../lib`,
Use `path.join`

2024-05-19 22:33 UTC, JoshuaBrest commented on src/backend/utils/compatibility_layers.ts
> +        type: `toolkit`,
Use normal string.

2024-05-20 23:01 UTC, ahmed2m commented
It seems that whisky's `CFBundleShortVersionString` in the package contents is not in sync with the Application Support one?

Whisky's latest version is indeed 2.3.2, but what's in the Application Support/Library/WhiskyWineVersion.plist is 2.2.0

Not idea why

---
Current Heroic :
<details>
<summary>Details</summary>

![CleanShot 2024-05-20 at 16 43 39@2x](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/26524089/fe2581bb-9530-4f3e-b6f4-2542f2e5a23f)


</details>


This MR CI build:

<details>


<summary>Details</summary>

![CleanShot 2024-05-20 at 16 44 38@2x](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/assets/26524089/f094f8dd-6033-40ef-9968-0b5c24347224)


</details>

2024-05-21 04:46 UTC, WangEdward commented
> Whisky's latest version is indeed 2.3.2, but what's in the Application Support/Library/WhiskyWineVersion.plist is 2.2.0

The version 2.2.0 is the same as [whisky's wine version](https://github.com/Whisky-App/wine/blob/7.7/WhiskyWineVersion.plist). It does not [update](https://github.com/Whisky-App/wine/commits/7.7/WhiskyWineVersion.plist) wine the same frequency it updates the [launcher](https://github.com/Whisky-App/Whisky/releases)(the .app itself)

2024-05-21 09:21 UTC, JoshuaBrest commented on src/backend/utils/compatibility_layers.ts
>    const whiskyWineBin = `${whiskyWinePath}/Wine/bin/wine64`
Can you update these too?

2024-11-18 13:10 UTC, flavioislima approved these changes
LGTM

2024-11-18 14:15 UTC, merged