Fix #386
Heroic-Games-Launcher/HeroicGamesLauncher pull request #387
Opened 2021-05-25 22:18 UTC by StefanLobbenmeier

New order of resolution for art_square: art_square -> art_cover -> fallBackImage

Should fix #386 where the image "DieselGameBoxTall" was missing in the JSON

2021-05-25 22:20 UTC, StefanLobbenmeier commented
This is what the cover now looks like on my machine:
![image](https://user-images.githubusercontent.com/36509607/119575979-26f2a380-bdb8-11eb-97f7-8649ea9d3b6d.png)

2021-05-25 22:32 UTC, flavioislima commented
Ah OK, you already got the fix. Nice.

2021-05-25 22:41 UTC, flavioislima requested changes
I think that instead of using the cover for the fallback, use the dieselStoreFrontTall type that comes with this game and probably others and then the cover. So it will look better.
So would be dieselGameBoxTall, if empty, DieselStoreFrontTall and last DieselGameBox.

👍

2021-06-03 08:12 UTC, flavioislima commented
@StefanLobbenmeier do you want to fix it or should we fix it?

2021-06-03 16:49 UTC, StefanLobbenmeier commented
Oh sorry hadn’t seen the first response. It’s probably less work for everyone if you fix it yourself since you already know exactly what you want :) 

I volunteer to get another screenshot after your path though

2021-06-03 18:19 UTC, adityaruplaha submitted a review, later dismissed

2021-06-03 18:23 UTC, flavioislima commented
@StefanLobbenmeier Can you confirm is working after my changes?

2021-06-03 23:00 UTC, StefanLobbenmeier commented
Thanks! Just tried it on MacOS, but the game list does not load. I will try again on Sunday on Linux

2021-06-05 17:29 UTC, StefanLobbenmeier commented
Ok fixed my issue for MacOS, the logs said
`/bin/sh: /Applications/Heroic: No such file or directory`
so I renamed the application from `Heroic Games Launcher` to `HeroicGamesLauncher` and the issue disappeared. Will open a separate issue for that.

Anyway after your changes the cover looks the same as with my approach, so it looks good to me:
![image](https://user-images.githubusercontent.com/36509607/120900289-5f09aa00-c634-11eb-85f0-8a486c521ee1.png)

2021-06-05 18:10 UTC, flavioislima commented
> Ok fixed my issue for MacOS, the logs said
> `/bin/sh: /Applications/Heroic: No such file or directory`
> so I renamed the application from `Heroic Games Launcher` to `HeroicGamesLauncher` and the issue disappeared. Will open a separate issue for that.
> 
> Anyway after your changes the cover looks the same as with my approach, so it looks good to me:
> ![image](https://user-images.githubusercontent.com/36509607/120900289-5f09aa00-c634-11eb-85f0-8a486c521ee1.png)
> 

Really? It should have worked with the change. Até you sure you're on the latest commit?

The mac version is complicated because we don't have a dedicated maintener so I don't even know if we will launch a installer for it. There are several things that needs to be done for it work as well.

2021-06-05 18:19 UTC, StefanLobbenmeier commented
I am on commit 521620abae366b7d3725b07b94e100b275da25f9, made a fresh checkout on another machine for this

2021-06-05 18:20 UTC, StefanLobbenmeier commented
```
➜  HeroicGamesLauncher git:(main) git log



commit 521620abae366b7d3725b07b94e100b275da25f9 (HEAD -> main, origin/main, orig
in/HEAD)
Merge: f77a4f2 6a35318
Author: Flávio F Lima <flavioislima@gmail.com>
Date:   Thu Jun 3 20:22:48 2021 +0200

    Merge branch 'main' into main

commit f77a4f268207b3bc6c24e975cce3920b84a73f67
Author: Flávio F Lima <flavioislima@gmail.com>
Date:   Thu Jun 3 20:20:17 2021 +0200

    chore: lint

commit 1f297b4eb3a5041a7bd7bc4af09b95d81d1b91c8
Author: Flávio F Lima <flavioislima@gmail.com>
Date:   Thu Jun 3 20:15:19 2021 +0200

    feat: added dieselStoreFrontTall as another fallback
```

2021-06-05 19:16 UTC, StefanLobbenmeier commented
I just checked your implementation via some debug logs:

```
        const artSquareResolved = art_square || art_square_front || art_cover || fallBackImage;
        console.log(app_name, art_square);
        console.log(app_name, art_square_front);
        console.log(app_name, art_cover);
        console.log(app_name, artSquareResolved);
```
```
JayDLC1 null
library.js:273JayDLC1 null
library.js:274JayDLC1 https://cdn1.epicgames.com/752368fdba244e9386023cfb2b9d6ceb/item/Sabotage_PicnicPanic-2560x1440-0466026af367640bd29a5052f326b1e7.jpg
library.js:275JayDLC1 https://cdn1.epicgames.com/752368fdba244e9386023cfb2b9d6ceb/item/Sabotage_PicnicPanic-2560x1440-0466026af367640bd29a5052f326b1e7.jpg
```

2021-06-05 19:20 UTC, StefanLobbenmeier commented on electron/legendary_utils/library.ts
> +      keyImages.filter(({ type }: KeyImage) => type === 'dieselStoreFrontTall' )[0] :
In the JSON in #386 dieselStoreFrontTall is actually uppercase DieselStoreFrontTall

2021-06-05 19:21 UTC, StefanLobbenmeier commented
After settings the String to uppercase I get another image now:
![Uploading image.png…]()

2021-06-05 19:39 UTC, flavioislima commented
Perfect, good catch!
I'll merge it then

2021-06-05 19:39 UTC, flavioislima approved these changes

2021-06-05 19:42 UTC, merged