LoginWarning Popup Automatic Close
Heroic-Games-Launcher/HeroicGamesLauncher pull request #3905
Opened 2024-08-06 18:33 UTC by alexho712

Added an onClick handler, called closeOnClick, to close the LoginWarning popup once the login path redirecting button on the popup is clicked so that users don't have to click both the button and the "x" when redirecting to the proper login path.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [x] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2024-08-06 18:33 UTC, flavioislima commented
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/doc/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

2024-08-06 18:51 UTC, imLinguin requested changes

2024-08-06 19:19 UTC, alexho712 commented on src/frontend/screens/Login/components/LoginWarning/index.tsx
> +        <NavLink className="button" to={loginPath} onClick={closeOnClick}>
Will do, changing it now

2024-08-06 19:37 UTC, imLinguin approved these changes

2024-08-09 15:48 UTC, flavioislima approved these changes
Thanks for the contribution

2024-08-09 15:48 UTC, merged