Render SelectFields as MUI Selects
Heroic-Games-Launcher/HeroicGamesLauncher pull request #4059
Opened 2024-10-14 11:41 UTC by CommandMC

This renders most drop-down selection prompts inside Heroic. In turn, these dropdowns now work inside the Gamescope session.

Current issues:
- [ ] Controller navigation does not work, hitting "Down" opens the dropdown, with no way to navigate further down to other components
- [ ] There is a black box in the top-left of the component, where the label should be

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2025-01-03 01:50 UTC, arielj requested changes
Looks good, but I left a comment about an accessibility feature that is not working with the new dialogs

2025-01-03 01:50 UTC, arielj commented on src/frontend/components/UI/Dialog/components/Dialog.tsx
> -      if (disableDialogBackdropClose) {
this was here to support the Accessibility option to disable the `close dialog when clicking outside` behavior. In this PR that's not working

2025-01-04 00:48 UTC, CommandMC commented on src/frontend/components/UI/Dialog/components/Dialog.tsx
> -      if (disableDialogBackdropClose) {
Whoops, somehow understood this as "Disable Esc key closing dialogs"
Fixed!

2025-01-04 01:16 UTC, arielj requested changes
There's one more thing I noticed, when using a RTL language, the arrow in the select field is in the wrong side of the element:

in `main`:
![image](https://github.com/user-attachments/assets/97df5bd8-6cd6-42fb-841e-a6a15e30ddbd)

with this changes:
![image](https://github.com/user-attachments/assets/332d1111-49e1-425c-af5c-3ccf3720b780)

2025-01-04 01:16 UTC, arielj commented on src/frontend/components/UI/SelectField/index.tsx
> +            paddingLeft: 0
can we use `paddingInlineStart: 0` here instead? it's better to support RTL languages since `inlineStart` is equivalent to `left` in LTR and `right` in RTL

2025-01-04 13:09 UTC, CommandMC commented on src/frontend/components/UI/SelectField/index.tsx
> +            paddingLeft: 0
I've ended up just using MUI's padding instead of ours, which also resolves an issue with excessive padding on RTL text

2025-01-06 03:13 UTC, arielj commented
I've been testing a bit more, I found 1 issue and two small things:

----------
one small thing is the `categories` and `filters` style changed and it's missing some padding:
- main:
![image](https://github.com/user-attachments/assets/c6aa9d86-4975-4a78-bac2-f265b9d1dc9e)

- this branch:
![image](https://github.com/user-attachments/assets/0c354c46-bf91-4100-a448-e768d9ad3345)

----------
the second small thing is that the controller hints (the instructions of what each button does at the bottom of the screen) shows incorrect hints for dropdowns, it thinks it's the context menu of library cards and it shows `( x ) Close Options` incorrectly. This one can be fixed by using `target.closest('.contextMenu')` in line 60 of src/frontend/components/UI/ControllerHints/index.tsx

---------
now the issue is that, when using a controller to navigate the UI (or a keyboard), you can get `stuck` focusing the `X` button of dialogs when the dialog's content is long and it shows a scrollbar:

- open the settings for a game
- in the `wine` tab (because it's long it will show a scrollbar), move `up` until you focus the `X`
- you can't move out of there (moving up/down scrolls the library page, moving left/right does nothing)

a smaller dialog doesn't have this problem:
- now use the mouse and change to the `other` tab (this is short and won't show a scrollbar)
- move `up` until you focus the `X`
- you can move out (moving up does nothing as expected, down/left/right moves focus to the tabs)

2025-05-19 21:50 UTC, arielj approved these changes

2025-05-19 22:04 UTC, merged