Fix capitalisation of Heroic in GlobalState.tsx
Heroic-Games-Launcher/HeroicGamesLauncher pull request #4218
Opened 2024-12-28 16:37 UTC by LenaWil

I noticed it while translating.

<--- Put the description here --->

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

2024-12-28 16:47 UTC, LenaWil commented
Am I stupid, or should [e2e](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/actions/runs/12528169796/job/34942495477?pr=4218) not fail?

2024-12-29 00:03 UTC, arielj requested changes
I think you need to run `pnpm i18n` so it updates the locale json file

2025-01-11 12:29 UTC, LenaWil commented
> I think you need to run `pnpm i18n` so it updates the locale json file

```
> heroic@2.15.2 i18n /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher
> i18next --silent

Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/__mocks__/@xhmikosr/decompress-unzip.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/__mocks__/config.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/__mocks__/constants.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/__mocks__/electron-store.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/__mocks__/electron.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/__mocks__/i18next.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/__tests__/cache.test.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/__tests__/constants.test.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/__tests__/main_window.test.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/__tests__/progress_bar.test.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/__tests__/skip.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/__tests__/utils.test.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/anticheat/ipc_handler.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/anticheat/utils.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/api/downloadmanager.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/api/helpers.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/api/index.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/api/library.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/api/menu.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/api/misc.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/api/settings.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/api/wine.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/backend_events.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/cache.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/config.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/constants.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/dialog/__mocks__/dialog.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/dialog/dialog.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/downloadmanager/downloadqueue.ts
Key is not a string literal
Key is not a string literal
Key is not a string literal
Key is not a string literal
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/downloadmanager/ipc_handler.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/downloadmanager/utils.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/electron_store.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/game_config.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/images_cache.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/launcher.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/logger/__mocks__/logfile.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/logger/__mocks__/logger.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/logger/__tests__/logfile.test.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/logger/__tests__/logger.test.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/logger/__tests__/uploader.test.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/logger/ipc_handler.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/logger/logfile.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/logger/logger.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/logger/uploader.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/main_window.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/main.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/online_monitor.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/preload.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/progress_bar.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/protocol.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/recent_games/ipc_handler.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/recent_games/recent_games.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/save_sync.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/schemas.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/shortcuts/ipc_handler.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/shortcuts/nonesteamgame/__tests__/nonesteamgame.test.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/shortcuts/nonesteamgame/constants.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/shortcuts/nonesteamgame/nonesteamgame.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/shortcuts/nonesteamgame/steamhelper.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/shortcuts/shortcuts/shortcuts.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/shortcuts/types.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/shortcuts/utils.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/gog/e2eMock.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/gog/electronStores.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/gog/games.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/gog/library.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/gog/presence.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/gog/redist.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/gog/setup.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/gog/user.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/index.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/legendary/__tests__/games.test.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/legendary/commands/auth.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/legendary/commands/base.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/legendary/commands/cleanup.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/legendary/commands/egl_sync.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/legendary/commands/eos_overlay.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeManagers/legendary/commands/import.ts
Parsing /Users/lena/Documents/Vrije tijd/HeroicGamesLauncher/src/backend/storeMana [...]

2025-01-21 18:17 UTC, LenaWil commented
@arielj Can you review again?

2025-01-22 01:25 UTC, arielj approved these changes
Looks good, thanks!

2025-01-22 01:25 UTC, merged