Fix error coverage report
Heroic-Games-Launcher/HeroicGamesLauncher pull request #446
Opened 2021-06-14 20:12 UTC by Nocccer

<--- Put the description here --->

----------------------------------

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Created / Updated Tests
- [ ] Created / Updated documentation

Tested on a Clean Install with AppImage:
- [ ] Login
- [ ] Download a Game
- [ ] Import a Game
- [ ] Launch Default config
- [ ] Launch Personalized Config
- [ ] Launch wine
- [ ] Launch Proton
- [ ] Launch Custom Proton
- [ ] Launch Tools (Winetricks and Winecfg)
- [ ] Uninstall Game
- [ ] Move Game
- [ ] Languages (Test if no translation stopped working)

2021-06-14 20:40 UTC, flavioislima commented
Looks good for this class but the others also must be inialialized to fix all errors.

2021-06-14 20:47 UTC, dragonDScript commented on electron/game_config.ts
>    public abstract version : GameConfigVersion
Declare version

2021-06-15 04:21 UTC, adityaruplaha approved these changes
Looks good, I'm not 100% sure we can get away with just `if (config)` after this though. I would initially set it to null and test if it was not null and only then proceed. 

But everything seems to be fine, so LGTM.

2021-06-15 17:02 UTC, flavioislima commented
The build will never work if you use `tsconfig` like this, they need to be different.
You need to keep in mind that the electron and the src folder are two complete different worlds, its the same logic we have on a web app, being the electron the backend and the src with react the frontend. We can have similar things, types, and share a few patterns, but they are not the same, that's why we have two different `tsconfig` files.

2021-06-15 19:03 UTC, closed without merging

2021-06-15 19:03 UTC, dragonDScript requested changes
Please fix these

2021-06-15 19:03 UTC, dragonDScript commented on electron/utils.ts
> +import { error } from 'console'
Same here. You should use './console'