Fix Issue 447
Heroic-Games-Launcher/HeroicGamesLauncher pull request #459
Opened 2021-06-17 17:20 UTC by dragonDScript

Same as #452

Use the following Checklist if you have changed something on the Backend or Frontend:

- [ ] Created / Updated Tests
- [ ] Created / Updated documentation

Tested on a Clean Install with AppImage:
- [ ] Login
- [ ] Download a Game
- [ ] Import a Game
- [ ] Launch Default config
- [ ] Launch Personalized Config
- [ ] Launch wine
- [ ] Launch Proton
- [ ] Launch Custom Proton
- [ ] Launch Tools (Winetricks and Winecfg)
- [ ] Uninstall Game
- [ ] Move Game
- [ ] Languages (Test if no translation stopped working)

2021-06-17 17:23 UTC, dragonDScript commented
Not my fault: 
TypeScript error in /home/runner/work/HeroicGamesLauncher/HeroicGamesLauncher/src/screens/Settings/index.tsx(283,15):
Type '{ egsPath: string; setEgsPath: Dispatch<SetStateAction<string>>; egsLinkedPath: string; setEgsLinkedPath: Dispatch<SetStateAction<string>>; ... 15 more ...; discordRPC: boolean; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'toggleDiscordRPC' does not exist on type 'IntrinsicAttributes & Props'.  TS2322

    281 |               toggleAddDesktopShortcuts={toggleAddDesktopShortcuts.toggle}
    282 |               toggleAddGamesToStartMenu={toggleAddGamesToStartMenu.toggle}
  > 283 |               toggleDiscordRPC={toggleDiscordRPC}
        |               ^
    284 |               discordRPC={discordRPC}
    285 |             />
    286 |           )}

wtf

2021-06-18 01:22 UTC, Nocccer commented
Checked main branch. Test passing locally. Create dist packages works. Can't reproduce your errors.

2021-06-18 08:13 UTC, dragonDScript commented
Please use squash and merge for future PRs

2021-06-18 08:21 UTC, flavioislima commented
> Please use squash and merge for future PRs

We  use it for merge into main.
i prefer it as well, but that was a long discussion some time ago. 
We can discuss this again since we have more devs now.

2021-06-18 08:23 UTC, dragonDScript commented
> > Please use squash and merge for future PRs
> 
> We use it for merge into main.
> i prefer it as well, but that was a long discussion some time ago.
> We can discuss this again since we have more devs now.

Okay. Here are my arguments: squash and merge lets you revert a PR at any time.

2021-06-18 08:31 UTC, dragonDScript commented
I fixed the conflicts.

2021-06-18 08:33 UTC, flavioislima commented
> > > Please use squash and merge for future PRs
> > 
> > 
> > We use it for merge into main.
> > i prefer it as well, but that was a long discussion some time ago.
> > We can discuss this again since we have more devs now.
> 
> Okay. Here are my arguments: squash and merge lets you revert a PR at any time.

Yes, that's why we do it in the main branch. If you check the PRs merged there, there is a revert button. :)

But for PRs I don't know if its possible to revert a specific commit, only if you merge a PR on another PR.

2021-06-18 08:38 UTC, flavioislima commented
> I fixed the conflicts.

i think there is still one left. To avoid conflicts with translations, is good not to change the locale files on a PR, since all of them are handled by weblate. 👍🏽

2021-06-19 09:56 UTC, dragonDScript commented
I've fixed the conflicts and still there is one left

2021-06-19 10:54 UTC, flavioislima requested changes

2021-06-19 10:54 UTC, flavioislima commented on electron/legendary/games.ts
> -    if (process.platform === 'win32'){
What happened here? Moved? Removed?

2021-06-19 10:54 UTC, flavioislima commented on electron/main.ts
> -  const egl_manifestPath = 'C:/ProgramData/Epic/EpicGamesLauncher/Data/Manifests'
Here as well. Looks like all windows fixes were removed.

2021-06-19 10:54 UTC, flavioislima commented on electron/main.ts
> -ipcMain.handle('showErrorBox', async (e, args: [title: string, message: string]) => {
Moved or removed?

2021-06-19 10:54 UTC, flavioislima commented on electron/legendary/games.ts
> -    const DiscordRPC = makeClient('852942976564723722')
Is this elsewhere?

2021-06-19 10:54 UTC, flavioislima commented on jest.config.js
> +    '<rootDir>/node_modules>',
I this line have an error. The > at the end I guess.

2021-06-19 11:23 UTC, flavioislima approved these changes
Looks good now 👍

2021-06-20 09:08 UTC, merged