Changed GitHub URL to the current one
Heroic-Games-Launcher/HeroicGamesLauncher pull request #514
Opened 2021-07-03 10:27 UTC by Flonky

Changed GitHub URL to the current one

----------------------------------

Use the following Checklist if you have changed something on the Backend or Frontend:

- Created / Updated documentation

Tested on a Clean Install with AppImage:
Not needed

2021-07-03 13:29 UTC, dragonDScript approved these changes

2021-07-04 08:59 UTC, Nocccer commented
Adapt tests too.

2021-07-04 08:59 UTC, Nocccer requested changes
Adapt tests too

2021-07-04 09:09 UTC, flavioislima commented
> Adapt tests too

The test failling is my fault, I'll fix it later.
And I think I'll also add yarn test to the pre-push script.

2021-07-04 09:09 UTC, flavioislima approved these changes

2021-07-04 09:09 UTC, merged